---
language: python
services: docker

install:
  - pip install molecule yamllint ansible-lint docker

script:
  - sh test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
